#▔\_(ツ)_/▔
messages:
  add-third: "§f§l>_§7 {PLAYER} hat dir eine Freundschaftsanfrage gesendet {#[RUN|/friend add {PLAYER}][§f[Akzeptieren]]#}"
  add-first: "§a§l>_§7 Du hast {PLAYER} eine Freundschaftsanfrage gesendet!"
  add-self: "§c§l>_§7 Du kannst dich nicht selbst als Freund hinzufügen!"
  accept-first: "§a§l>_§7 Du bist nun mit {PLAYER} befreundet!"
  accept-third: "§a§l>_§7 {PLAYER} hat deine Freundschaftsanfrage akzeptiert!"
  remove-first: "§c§l>_§7 Du bist jetzt nicht mehr mit {PLAYER} befreundet!"
  remove-thid: "§c§l>_§7 {PLAYER} hat dich als Freund entfernt!"
  duplicate: "§c§l>_§7 Du bist bereits mit {PLAYER} befreundet!"
  not-found: "§c§l>_§7 ZOMG! Spieler nicht gefunden..."
  not-friends: "§c§l>_§7 Du bist nicht mit {PLAYER} befreundet!"
  no-friends: "§c§l>_§7 Deine Freundesliste ist leer!"
  syntax-add: "§c§l>_§7 Syntax: /friend add [Name]"
  error: "§c§l>_§7 ZOMG! Ein Fehler ist aufgetreten..."
  list-header: "§7---------< §fFreundesliste §7>---------"
  list: "§7> {PLAYER} §8: {DATE}"
  help:
    - "§7---------< §fHilfemenü - Freunde §7>---------"
    - "§7> Alias: §f/f"
    - "§7> Argumente: {#[SUGGEST|/friend add][§fadd]#} §7/ {#[SUGGEST|/friend remove][§fremove]#} §7/ {#[RUN|/friend list][§flist]#}"