mysql:
  server: 127.0.0.1
  port: 3306
  username: admin
  password: 123
  database: pcs_economy

economy:
  messagePrefix: "§b[§aEconomy§b]§f"
  pushInterval: 10
  currency:
    currencySingular: Schekel
    currencyPlural: Schekel
    currencySymbol: ש
  permissions:
    admin: pcs.economy.admin
    user: pcs.economy.user
  messages:
    success:
      successGeneral: Alles gut
    error:
      errorGeneral: Irgendwas ist schief gelaufen. Bitte kontaktiere einen Admin
    action:
      accounts:
        success:
          accountSuccessBalanceSelf: "{PREFIX} Kontostand: §l§6{CSYMBOL}{AMOUNT}§r§f"
          accountSuccessBalanceOther: "{PREFIX} Kontostand von §2{PLAYER}§f: §l§6{CSYMBOL}{AMOUNT}§r§f"
          accountSuccessDelete: "{PREFIX} Konto von §2{PLAYER}§f erfolgreich gelöscht!"
          accountSuccessClear: "{PREFIX} Konto von §2{PLAYER}§f erfolgreich auf 0 gesetzt!"
          accountSuccessCreate: "{PREFIX} Konto von §2{PLAYER}§f erfolgreich erstellt!"
          accountSuccessSet: "{PREFIX} Kontostand von §2{PLAYER}§f erfolgreich auf §l§6{CSYMBOL}{AMOUNT}§r§f gesetzt!"
          accountSuccessAdd: "{PREFIX} Es wurden dem Konto von §2{PLAYER}§f §l§6{CSYMBOL}{AMOUNT}§r§f hinzugefügt!"
          accountSuccessSubtract: "{PREFIX} Es wurden dem Konto von §2{PLAYER}§f §l§6{CSYMBOL}{AMOUNT}§r§f abgezogen!"
        error:
          accountErrorBalanceSelf: "{PREFIX} Dein Kontostand konnte nicht abgerufen werden!"
          accountErrorBalanceOther: "{PREFIX} Der Kontostand von §2{PLAYER}§f konnte nicht abgerufen werden!"
          accountErrorDelete: "{PREFIX} Konto von §2{PLAYER}§f konnte nicht gelöscht werden!"
          accountErrorClear: "{PREFIX} Konto von §2{PLAYER}§f konnte nicht auf 0 gesetzt werden!"
          accountErrorCreate: "{PREFIX} Konto von §2{PLAYER}§f konnte nicht erstellt werden!"
          accountErrorSet: "{PREFIX} Kontostand von §2{PLAYER}§f konnte nicht gesetzt werden!"
          accountErrorAdd: "{PREFIX} Konnte den Betrag dem Konto von §2{PLAYER}§f nicht hinzufügen!"
          accountErrorSubtract: "{PREFIX} Konnte den Betrag dem Konto von §2{PLAYER}§f nicht abziehen!"
    payment:
      error:
        paymentError: "{PREFIX} Transaktion fehlgeschlagen"
        paymentErrorNegativeValue: "{PREFIX} Negative Werte sind nicht erlaubt"
        paymentErrorNotEnoughFunds: "{PREFIX} Du hast nicht genügend Geld auf dem Konto"
        paymentErrorAccountNotExisting: "{PREFIX} Das angegebene Konto existiert nicht"
        paymentErrorSelf: "{PREFIX} Du kannst kein Geld an dich selbst überweisen"
      success:
        paymentSuccessSender: "{PREFIX} Es wurden erfolgreich §l§6{CSYMBOL}{AMOUNT}§r§f an §2{PLAYER}§f überwiesen!"
        paymentSuccessReceiver: "{PREFIX} Du hast gerade §l§6{CSYMBOL}{AMOUNT}§r§f von §2{PLAYER}§f erhalten!"
    permission:
      errorNoPermission: "{PREFIX} Du hast keine Berechtigung diesen Command zu nutzen!"
    shop:
      trader:
        errorRemoveTrader: "{PREFIX} Trader konnte nicht gelöscht werden!"
        successRemoveTrader: "{PREFIX} Trader erfolgreich gelöscht!"
        successCreateTrader: "{PREFIX} Trader erfolgreich erstellt!"
  gui:
    selection:
      sellPrice: "Preis pro Stück: §6{AMOUNT}"
      buyPrice: "Ankaufspreis pro Stück: §6{AMOUNT}"
    trade:
      quantity: "§5* §7Anzahl: §5{AMOUNT}"
      cost: "§5* §7Preis: §6{AMOUNT}{CSYMBOL}"
      information: "§aInformation:"
      back: Kehre zur Übersicht zurück
      notEnoughFunds: §4Du hast nicht genügend Geld auf dem Konto!
      inventoryFull: §4Dein Inventar ist voll!
      notEnoughItems: §4Du hast nicht genug Items!
      sell:
        errorCantSell: §4Das Item wird hier nicht verkauft!
        titleSingle: §a§nKaufe Eins
        titleStack: §a§nKaufe Stack
        titleInv: §a§nKaufe Inventar
        descriptionSingle: §8Kaufe ein einzelnes Item
        descriptionStack: §8Kaufe einen Stack Items
        descriptionInv: §8Kaufe so viel wie dein Inventar Platz hat
        sell: §4(!) Klicken um zu kaufen!
      buy:
        errorCantBuy: §4Das Item wird hier nicht gekauft!
        titleSingle: §a§nVerkaufe Eins
        titleStack: §a§nVerkaufe Stack
        titleInv: §a§nVerkaufe Inventar
        descriptionSingle: §8Verkaufe ein einzelnes Item
        descriptionStack: §8Verkaufe einen Stack Items
        descriptionInv: §8Verkaufe dein ganzes Inventar
        purchase: §4(!) Klicken um zu verkaufen!
