name: PCS_Essentials
author: Flare
version: ${project.version}
main: com.z0cken.mc.essentials.PCS_Essentials
depend: [PCS_Core]
softdepend: [PCS_Claim, Vault, WorldGuard]
api-version: 1.13

commands:
  pcse:
  award:
    permission: pcs.essentials.award
  erosion:
    permission: pcs.essentials.erosion
  wild:
    permission: pcs.essentials.wild
  help:

permissions:
  pcs.essentials.*:
    children:
      pcs.essentials.snowball: true
      pcs.essentials.award: true
      pcs.essentials.erosion: true
      pcs.essentials.wild: true