revive-toter: '§7PLAYER §ahat dich wiederbelebt!'
revive-spieler: '§aDu hast erfolgreich §7PLAYER §awiederbelebt!'
nicht-tot-error: '§cDu kannst diesen Befehl nur nutzen, wenn du tot bist.'
force-ohne-ziel-error: '§cDu kannst diesen Befehl ohne Ziel nicht von der Konsole aus benutzen. Bitte geben einen Spieler an den du wiederbeleben willst. /respawn <player>'
respawn-toter-force: '§7PLAYER §ahat deinen Respawn erzwungen.'
respawn-sender-force: '§aDu hast den Respawn von §7PLAYER §aerfolgreich erzwungen.'
force-ziel-lebend-error: '§7PLAYER §cist nicht tot!'
force-ziel-unbekannt-error: '§cSpieler §7ARG0 §cexistiert nicht.'
respawn-command: '§aKlick hier um frühzeitig zu respawnen.'